name: SmallAdditions
version: ${project.version}
main: me.gigawartrex.smalladditions.main.SmallAdditions
api-version: 1.18
#prefix: SmallAdditions
author: Paul Ferlitz
description: Small additions to Minecraft making it just slightly better.

commands:
  sa:
    description: Base SimpleAdditions command.
    usage: /<command> <book | menu | invsee | enderinvsee>
  sa book:
    description: Gives the player the README book.
    usage: /<command>
  sa menu:
    description: Opens the SimpleAdditions menu.
    usage: /<command>
  sa invsee:
    description: Look into a player's inventory.
    usage: /<command> <playername>
  sa enderinvsee:
    description: Look into a player's enderchest.
    usage: /<command> <playername>
  sa resetall:
    description: Resets all files and statistics.
    usage: /<command>
  sa hide:
    description: Let's a player hide from others and not be displayed on scoreboards etc.
    usage: /<command>
  sa ninjajoin:
    description: Let's a player join without the join message beeing displayed.
    usage: /<command>