name: SmallAdditions
version: 1.0-SNAPSHOT
main: me.gigawartrex.smalladditions.main.SmallAdditions
api-version: 1.16
#prefix: SmallAdditions
author: Paul Ferlitz
description: Small additions to Minecraft making it just slightly better.

commands:
  sa:
    description: Base SimpleAdditions command.
    usage: /<command> [option]
  sa book:
    description: Gives the player the README book.
    usage: /<command>
  sa menu:
    description: Opens the SimpleAdditions menu.
    usage: /<command>
  sa invsee:
    description: Look into a player's inventory.
    usage: /<command> [playername]
  sa enderinvsee:
    description: Look into a player's enderchest.
    usage: /<command> [playername]
  sa resetall:
    description: Resets all files and statistics.
    usage: /<command>