name: SmallAdditions
version: 1.0-SNAPSHOT
main: me.gigawartrex.smalladditions.main.SmallAdditions
api-version: 1.13
#prefix: SmallAdditions
author: Paul Ferlitz
authors:
description: Small additions to Minecraft making it just slightly better.

commands:
  sa:
    description: Base Command
    usage: /<command>